### Get All Projects
GET http://localhost:8080/projects

### Get Project
GET http://localhost:8080/projects/1

### Create Project
POST http://localhost:8080/projects
Content-Type: application/json

{
    "name" : "Proyecto nuevo"
}

### Update Project
PUT http://localhost:8080/projects/1
Content-Type: application/json

{
    "name" : "Cambio de nombre"
}

### Delete Project
DELETE http://localhost:8080/projects/1